services:
  # BACKEND (Node)
  - type: web
    name: campus-navigator-backend
    env: node
    plan: free
    branch: main
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://diwakargunasekhar_db_user:Enter%40123@cluster0.uwfvyzn.mongodb.net/campus_navigator?retryWrites=true&w=majority
      - key: NODE_ENV
        value: production

  # FRONTEND (Static)
  - type: web
    name: campus-navigator-frontend
    env: static
    plan: free
    branch: main
    buildCommand: ""
    staticPublishPath: .
