services:
  # BACKEND (Node)
  - type: web
    name: campus-navigator-backend
    env: node
    plan: free
    region: oregon
    branch: main
    root: backend
    buildCommand: npm install
    startCommand: npm start

  # FRONTEND (static)
  - type: web
    name: campus-navigator-frontend
    env: static
    plan: free
    region: oregon
    branch: main
    root: .
    buildCommand: ""
    staticPublishPath: .
